### ISSUE TITLE
Support all XLA element types

### ISSUE THREAD

**Issue by Ebanflo42** [BradenEverson/unda#33]
This should be a pretty simple one, xla-rs has an enum

```
pub enum ElementType {
    Pred,
    S8,
    S16,
    S32,
    S64,
    U8,
    U16,
    U32,
    U64,
    F16,
    F32,
    Bf16,
    F64,
    C64,
    C128,
}
```

`Pred` is `bool` and `C` stands for complex. This should mesh easily if the numpy importing is already working. This can also be solved in the same branch as #28 and #29

**Comment by BradenEverson** [comment]
What's the Bf16 stand for?
