### ISSUE TITLE
Operations for Dense Networks

### ISSUE THREAD

**Issue by Ebanflo42** [BradenEverson/unda#40]
We still need to bind and write differentiation rules for the following operations to train dense networks:
`matmul`
`transpose`
`log`
`div`
`pow`
`reduce_sum`
`reduce_mean`
In order to differentiate the last two we need a `repeat` or `tile` operation, which is apparently not yet bound in `xla-rs`. We also need a `scatter` operation in order to differentiate `reduce_max` and `slice_in_dim`, so I might look into adding bindings to xla-rs.

**Comment by Ebanflo42** [comment]
Also `exp`, I somehow forgot `exp`

**Comment by Ebanflo42** [comment]
Leftover operations: `matmul`, `transpose`, `log`, `exp`, `pow`

**Comment by BradenEverson** [comment]
`exp` finished too now

**Comment by BradenEverson** [comment]
Just `matmul` and `transpose` left now
